language: rust
branches:
  only:
    - master

cache:
  directories:
  - ~/.cargo
  - target
before_cache:
  - cargo install cargo-cache --no-default-features --features ci-autoclean cargo-cache
  - cargo cache
install:
  - export CARGO_TARGET_DIR=$TRAVIS_BUILD_DIR/target
  - cargo install mdbook
script:
  - ./generate-book.sh

env:
  RUSTINFRA_DEPLOY_DIR: book
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml
